### ISSUE TITLE
Connect the File Service Manager to Kafka to process events 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/files-service#19]
- [ ]  connect to Kafka to read ANALYSIS published event 
- [ ]  connect to Kafka to read ANALYSIS unpublished event 
- [ ]  connect to Kafka to read ANALYSIS suppressed event 

## Expected Outcome 
- When an analysis is published, a `file` record is created in the file-service

**Comment by blabadi** [comment]
files service is now listening to `song_analysis` topic 

- publish an analysis (in song.rdpc-qa)
- when the event reaches platform to song_analysis topic
- files service will pick it up, if the analysisState is `PUBLISHED`, it will index, otherwise delete the files
- the file should be added to files service
- it should also be visible in Kibana search query `GET /file_centric_next/_search`
